#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use AppBundle\Command\DomainCommand;

const ROOTDIR = __DIR__;

$application = new Application();
$application->add(new DomainCommand());

$application->run();